// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4XesyGuZ20Two7XFjwAcvpMhHyxr-JeA',
    appId: '1:296783775724:ios:0c0d669531fac750ca22c9',
    messagingSenderId: '296783775724',
    projectId: 'quizbit-a11f7',
    storageBucket: 'quizbit-a11f7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIaNVtxEMSDKem3pGxtIQpYsvb6z8mZDc',
    appId: '1:296783775724:web:ca9c06120461c8cdca22c9',
    messagingSenderId: '296783775724',
    projectId: 'quizbit-a11f7',
    authDomain: 'quizbit-a11f7.firebaseapp.com',
    storageBucket: 'quizbit-a11f7.firebasestorage.app',
    measurementId: 'G-CWTXPQ79KC',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIaNVtxEMSDKem3pGxtIQpYsvb6z8mZDc',
    appId: '1:296783775724:web:ca9c06120461c8cdca22c9',
    messagingSenderId: '296783775724',
    projectId: 'quizbit-a11f7',
    authDomain: 'quizbit-a11f7.firebaseapp.com',
    storageBucket: 'quizbit-a11f7.firebasestorage.app',
    measurementId: 'G-CWTXPQ79KC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4XesyGuZ20Two7XFjwAcvpMhHyxr-JeA',
    appId: '1:296783775724:ios:0c0d669531fac750ca22c9',
    messagingSenderId: '296783775724',
    projectId: 'quizbit-a11f7',
    storageBucket: 'quizbit-a11f7.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnK3vs5IBCf-z-bz_sqoTnjZMd346bu5k',
    appId: '1:296783775724:android:ba49caf802b01ccaca22c9',
    messagingSenderId: '296783775724',
    projectId: 'quizbit-a11f7',
    storageBucket: 'quizbit-a11f7.firebasestorage.app',
  );

}